[package]
name = "google"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.0"
ansi_term = "0.12"
clap = { version = "4.0", features = ["derive"] }
